### ISSUE TITLE
Phone firmware distribution

### ISSUE THREAD

**Issue by DavidePrincipi** [nethesis/dev#5776]
The admin wants to massively upgrade the firmware of multiple phones. Typical scenario could be

1. test the upgrade on a couple of phones of model X
2. if the test is successful deploy the upgrade on all phones of model X 

The NethVoice provisioning based on Tancredi has to allow

1. upload the new firmware file into a server directory
2. select a firmware file among those already uploaded (latest uploads must to be found with ease)
3. associate a firmware file to a single phone or a model, so the upgrade is automatically started on the next provision round

**TODO list**

- [x] frontend analysis
- [x] backend analysis
- [x] template for Fanvil
- [x] template for Yealink
- [x] template for Snom
- [x] template for Sangoma
- [x] template for Gigaset

**Components**

- nethserver-tancredi
- nethvoice-wizard-ui

**Comment by nethbot** [comment]
in `7.7.1908/nethesis-testing`:
- nethserver-tancredi-1.1.1-1.2.gf101255.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.7.1908/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.1-1.2.gf101255.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.7.1908/nethesis-testing`:
- nethserver-tancredi-1.1.1-1.3.g513dea7.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.7.1908/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.1-1.3.g513dea7.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.7.1908/nethesis-testing`:
- nethserver-tancredi-1.1.1-1.4.g00dbb19.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.7.1908/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.1-1.4.g00dbb19.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
**Test case 0** (provisioning backend)

Send HTTP GET requests to `/provisioning/TOKEN/firmware/FILE` (e.g. `curl -v http://vm7.dpnet.nethesis.it/provisioning/10305875265ea07f6caf5bc1.19935029/firmware/xml.png`):

1) If TOKEN is not valid, 404 is returned
2) If FILE does not exist under `/var/lib/tancredi/data/firmware` , 404 is returned
3) If FILE exists under `/var/lib/tancredi/data/firmware` the file contents are returned

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.1-1.5.g06aba1c.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.1-1.5.g06aba1c.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.1-1.6.gf1bd3c9.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.1-1.6.gf1bd3c9.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.1-1.7.gf46ea15.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.1-1.7.gf46ea15.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-updates`:
- nethserver-tancredi-1.1.2-1.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-updates/x86_64/Packages/nethserver-tancredi-1.1.2-1.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
The backend /provisioning/firmware endpoint has been released

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.2-1.1.g8874e5a.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.2-1.1.g8874e5a.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
**Test case 0**

See above comment https://github.com/nethesis/dev/issues/5776#issuecomment-620005848

**Test case 1**

Any phone from Fanvil, Yealink, Snom, Gigaset and Sangoma can upgrade its firmware during the scheduled provisioning time.

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.2-1.4.g85f57f6.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.2-1.4.g85f57f6.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.2-1.6.gb575a77.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.2-1.6.gb575a77.ns7.noarch.rpm)

**Comment by DavidePrincipi** [comment]
**VERIFIED**

...At least for Fanvil X4U

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.2-1.7.gea645ca.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.2-1.7.gea645ca.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-testing`:
- nethserver-tancredi-1.1.2-1.8.g3f8737c.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.1.2-1.8.g3f8737c.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.8.2003/nethesis-updates`:
- nethserver-tancredi-1.2.0-1.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-updates/x86_64/Packages/nethserver-tancredi-1.2.0-1.ns7.noarch.rpm)
