### ISSUE TITLE
NethVoice: new CDR/Costs report

### ISSUE THREAD

**Issue by gsanchietti** [nethesis/dev#5907]
This issue is used to track all the development process of the new cdr/costs reports of NethVoice.

Things to do:
- [x] CDR/Costs UI structure:
  -  Dashboard
  -  PBX Data
      - Inbound calls
      - Outbound calls
      - Local calls
  - Personal data
      - Inbound calls
      - Outbound calls
      - Local calls

  -  Settings: cost configuration

- [x] APIs for cdr/costs reports
- [x] Tasks for cdr/costs reports

**See also**
- [Requirements](https://docs.google.com/document/d/1tEs2uW1yYOBqe0mHzGDT5xTxwiESe4vNW9OrPqQSB1w/edit#heading=h.6o2kl1xlfmw1)
- #5865 

**Repo reference**
https://github.com/nethesis/nethvoice-report

**Comment by andre8244** [comment]
**TODO**

- Bug
- [x] Saved search can contain dashes, but an error validation is issued
- [x] Tasks queries: `Error retrieving query tree [STATUS]: 404`
- [x] Tasks: `views` task cannot complete
- [x] Uncomment view `performance_talk_time_total`
- [x] Uncomment view `data_summary_agent_*`
- [x] Saved searches not working
- [x] `nullcall`: new admin settings. Edit `views` queries and use template engine
- [x] UI for `nullcall` setting
- [x] Remove Destination filter from Graph/By hour
---

- Alpha
- [x] Doc-info at the top of CDR pages
- [x] Verify data/summary graphs
- [x] Costs: test computation and update
- [x] Test pbx and personal queries
- [x] Queries: verify CDR and recap `WHERE`, they must be equal
- [x] CDR/Call detail: verify columns
- [x] Remove groups filter
- [x] Dashboard queries
- [x] Humanize totals in pie chart tooltip
- [x] Verify end time of nightly tasks
- [x] FixedBar: test active filters
- [x] Time range for dashboard
- [x] Admin settings: specific validation errors
- [x] Filters: distinguish searches saved on queue report from those saved on CDR report
- [x] Export: add `deviceSrc` and `deviceDst` before export
- [x] CDR: format cost column
- [x] i18n for `src ` / `dst` columns ("hangup", "busy", ...)
- [x] Left menu: i18n tags search 
- [x] CDR: remove cost column in inbound and local
- [x] Recap: remove outbound and local card in incoming view, and so on
- [x] CDR: phonebook reverse lookup for `src ` / `dst` columns. Show icon and tooltip
- [x] Merge admin settings from configuration and cache, using reflect
- [x] CDR: show local users name in `src` / `dst` columns
---

- Beta
- [x] Full documentation
- [x] Charts: export PNG
- [x] Country flag near international phone numbers
- [x] New logo in login page and favicon
- [x] Filters: docinfo for call duration ("You can type a custom duration in seconds")
- [x] Filters: docinfo for `caller` and `callee` ("Search for a contact or type a phone number")
- [x] Filters: test phonebook contact with multiple phone numbers
- [x] Time interval: prevent selection of dates with no data (use `cdr_first_month`)
---

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.177.g336f515.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.177.g336f515.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.177.g336f515.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.177.g336f515.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.179.gde699a6.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.179.gde699a6.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.179.gde699a6.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.179.gde699a6.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.180.g81ec867.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.180.g81ec867.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.180.g81ec867.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.180.g81ec867.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.182.g36d3e47.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.182.g36d3e47.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.182.g36d3e47.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.182.g36d3e47.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.183.g0930858.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.183.g0930858.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.183.g0930858.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.183.g0930858.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.184.g1fb73ca.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.184.g1fb73ca.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.184.g1fb73ca.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.184.g1fb73ca.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.185.g01e86e4.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.185.g01e86e4.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.185.g01e86e4.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.185.g01e86e4.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.186.ge789e74.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.186.ge789e74.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.186.ge789e74.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.186.ge789e74.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.187.g98bc137.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.187.g98bc137.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.187.g98bc137.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.187.g98bc137.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.188.g8a46b53.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.188.g8a46b53.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.188.g8a46b53.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.188.g8a46b53.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.189.gfffd4da.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.189.gfffd4da.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.189.gfffd4da.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.189.gfffd4da.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.190.gef678f0.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.190.gef678f0.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.190.gef678f0.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.190.gef678f0.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.191.gb6c53f0.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.191.gb6c53f0.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.191.gb6c53f0.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.191.gb6c53f0.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.192.ge0cc61a.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.192.ge0cc61a.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.192.ge0cc61a.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.192.ge0cc61a.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.193.gc686502.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.193.gc686502.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.193.gc686502.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.193.gc686502.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.194.gc752f5a.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.194.gc752f5a.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.194.gc752f5a.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.194.gc752f5a.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.195.g3312906.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.195.g3312906.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.195.g3312906.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.195.g3312906.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.196.g9b59844.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.196.g9b59844.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.196.g9b59844.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.196.g9b59844.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.197.g88b7512.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.197.g88b7512.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.197.g88b7512.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.197.g88b7512.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethserver-nethvoice14-14.9.0-1.1.g9cfb694.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethserver-nethvoice14-14.9.0-1.1.g9cfb694.ns7.noarch.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.198.g1ea41fc.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.198.g1ea41fc.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.198.g1ea41fc.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.198.g1ea41fc.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.201.ga8f3138.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.201.ga8f3138.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.201.ga8f3138.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.201.ga8f3138.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethvoice-report-0.1.2-1.202.gfaef78d.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-0.1.2-1.202.gfaef78d.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.1.2-1.202.gfaef78d.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-report-debuginfo-0.1.2-1.202.gfaef78d.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-updates`:
- nethvoice-report-0.2.0-1.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethvoice-report-0.2.0-1.ns7.x86_64.rpm) 
- nethvoice-report-debuginfo-0.2.0-1.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethvoice-report-debuginfo-0.2.0-1.ns7.x86_64.rpm)
