### ISSUE TITLE
Add param URL to nethifier

### ISSUE THREAD

**Issue by b9874e** [nethesis/dev#6141]
Implement the param URL functionality inside nethifier.
The param URL must work in the same way as in nethcti.

By default the param url must be disabled and can be set to:
- Open URL on ringing
- Open URL on answer

**Tasks**
- [x] Add the uniqueId to the notification event in server
- [x] Manage users choice on nethifier
- [x] Implement the param URL flow on events

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti-server3-3.28.1-1.8.g7ef345a.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.1-1.8.g7ef345a.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.1-1.8.g7ef345a.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.1-1.8.g7ef345a.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti-server3-3.28.1-1.9.g93f163c.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.1-1.9.g93f163c.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.1-1.9.g93f163c.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.1-1.9.g93f163c.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti-server3-3.28.1-1.10.gba44f2c.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.1-1.10.gba44f2c.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.1-1.10.gba44f2c.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.1-1.10.gba44f2c.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti-server3-3.28.1-1.11.gd02c0a2.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.1-1.11.gd02c0a2.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.1-1.11.gd02c0a2.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.1-1.11.gd02c0a2.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti-server3-3.28.1-1.12.g09942a0.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.1-1.12.g09942a0.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.1-1.12.g09942a0.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.1-1.12.g09942a0.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti-server3-3.28.1-1.13.g3d6b26f.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.1-1.13.g3d6b26f.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.1-1.13.g3d6b26f.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.1-1.13.g3d6b26f.ns7.x86_64.rpm)

**Comment by nethbot** [comment]
in `7.9.2009/nethesis-updates`:
- nethcti-server3-3.28.2-1.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethcti-server3-3.28.2-1.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.2-1.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethcti-server3-debuginfo-3.28.2-1.ns7.x86_64.rpm)
